<div class="col-6">
  <h1>Contact Form - Confirm</h1>
  <form class="confirm" method="post" action="./">
    <div class="mb-3">
      <label for="name" class="form-label">名前</label>
      <div class="confirm-value name">aaaaaaaaaa</div>
      <input type="hidden" name="name" value="" />
    </div>

    <div class="mb-3">
      <label for="furigana" class="form-label">フリガナ</label>
      <div class="confirm-value furigana">aaaaaaaaaa</div>
      <input type="hidden" name="furigana" value="" />
    </div>

    <div class="mb-3">
      <label for="email" class="form-label">メールアドレス</label>
      <div class="confirm-value email">aaaaaaaaaa</div>
      <input type="hidden" name="email" value="" />
    </div>

    <div class="mb-3">
      <label for="category" class="form-label">お問い合わせ項目</label>
      <div class="confirm-value category">aaaaaaaaaa</div>
      <input type="hidden" name="category" value="" />
    </div>

    <div class="mb-3">
      <label for="body" class="form-label">内容</label>
      <div class="confirm-value body">
        aaaaaaaaaa<br />
        aaaaaaaaaa<br />
        aaaaaaaaaa<br />
        aaaaaaaaaa<br />
        aaaaaaaaaa<br />
        aaaaaaaaaa<br />
        aaaaaaaaaa<br />
        aaaaaaaaaa<br />
        aaaaaaaaaa<br />
        aaaaaaaaaa<br />
        aaaaaaaaaa<br />
        aaaaaaaaaa
      </div>
      <input type="hidden" name="body" value="" />
    </div>

    <div class="buttons">
      <input type="hidden" name="rnd" value="" />
      <button type="submit" class="btn btn-outline-primary" name="cmd" value="input">Cancel</button>
      <button type="submit" class="btn btn-primary" name="cmd" value="done">Submit</button>
    </div>
  </form>
</div>

